oewoboka/oewoboka.xcodeproj/project.pbxproj, oewoboka/oewoboka/Helper/Constant.swift, oewoboka/oewoboka/Scenes/FeaturePage/FeatureCollectionViewCell.swift, oewoboka/oewoboka/Scenes/FeaturePage/FeatureViewController.swift, oewoboka/oewoboka/Scenes/FeaturePage/FeatureViewModel.swift, oewoboka/oewoboka/Scenes/FeaturePage/Models/FeatureCellModels.swift
=> #4 [FEAT] Constant 추가 및 cellModel 분리

oewoboka/oewoboka.xcodeproj/project.pbxproj, oewoboka/oewoboka/Helper/Typography.swift, oewoboka/oewoboka/View/DefaultButton.swift
Typography 파일에 기본으로 적용시킬 폰트를 추가하였고
DefaultButton 클래스로 겹치는 버튼의 기본 값들을 넣어 추가해 놓았습니다.
1. center: 이미지가 왼쪽에 있고 텍스트가 가운데에 있는 형태
2. left: 이미지와 텍스트가 왼쪽에 모여있는 형태
3. rightImage: 오른쪽 끝에 이미지를 추가 할 수 있는 형태 
4. noBorder: border가 없는 형태
=> [FEAT] 기본 폰트 설정 및 기본 버튼 클래스 추가  @three523 Issue#7

oewoboka/oewoboka/Scenes/TabBarController.swift
=> [FEAT] TabbarUI 기초 UI작업

oewoboka/oewoboka.xcodeproj/project.pbxproj, oewoboka/oewoboka/Enum/QuizResultType.swift, oewoboka/oewoboka/Enum/QuizType.swift, oewoboka/oewoboka/Helper/BottomSheetViewController.swift, oewoboka/oewoboka/Resource/SceneDelegate.swift, oewoboka/oewoboka/Scenes/AnswerPage/AnswerViewController.swift, oewoboka/oewoboka/Scenes/AnswerPage/BottomSheetPresentationController.swift, oewoboka/oewoboka/Scenes/AnswerPage/Cell/AnswerTableViewCell.swift, oewoboka/oewoboka/Scenes/AnswerPage/View/BottomView.swift, oewoboka/oewoboka/Scenes/AnswerPage/View/TopView.swift, oewoboka/oewoboka/Scenes/QuizCompletePage/QuizCompleteViewController.swift, oewoboka/oewoboka/Scenes/QuizCompletePage/View/FeedBackStackView.swift, oewoboka/oewoboka/Scenes/QuizCompletePage/View/ResultView.swift, oewoboka/oewoboka/Scenes/QuizPage/Model/Vocabulary.swift, oewoboka/oewoboka/Scenes/QuizPage/Model/Word.swift, oewoboka/oewoboka/Scenes/QuizPage/QuizViewController.swift, oewoboka/oewoboka/Scenes/QuizPage/View/CardView.swift, oewoboka/oewoboka/Scenes/QuizPage/View/QuizControlStackView.swift, oewoboka/oewoboka/View/DefaultButton.swift
Quiz 화면 UI 구현 & BottomSheetViewController 클래스 생성
BottomSheetViewController : BottomSheet 처럼 view의 상단을 드래그로 닫을수 있도록 하는 뷰 컨트롤러 클래스
#1
=> Quiz 페이지 UI 구현 & BottomSheetViewController 클래스 생성

oewoboka/oewoboka.xcodeproj/project.pbxproj, oewoboka/oewoboka/Helper/Typography.swift, oewoboka/oewoboka/Resource/SceneDelegate.swift, oewoboka/oewoboka/Scenes/VocaListPage/SelectedVocaViewController.swift, oewoboka/oewoboka/Scenes/VocaListPage/VocaListTableViewCell.swift, oewoboka/oewoboka/Scenes/VocaListPage/VocaListViewController.swift, oewoboka/oewoboka/Scenes/VocaListPage/VocaTableViewCell.swift, oewoboka/oewoboka/Scenes/VocaListPage/VocaViewController.swift
=> [Feat]: VocaListPage UI 작업

oewoboka/oewoboka.xcodeproj/project.pbxproj, oewoboka/oewoboka/Model/Model.xcdatamodeld/Model.xcdatamodel/contents, oewoboka/oewoboka/Model/VocabularyRepository.swift, oewoboka/oewoboka/Scenes/AnswerPage/AnswerViewController.swift, oewoboka/oewoboka/Scenes/FeaturePage/FTModalPage/FTOPViewController.swift, oewoboka/oewoboka/Scenes/FeaturePage/Models.swift, oewoboka/oewoboka/Scenes/QuizCompletePage/QuizCompleteViewController.swift, oewoboka/oewoboka/Scenes/QuizPage/Model/Vocabulary.swift, oewoboka/oewoboka/Scenes/QuizPage/Model/Word.swift, oewoboka/oewoboka/Scenes/QuizPage/QuizViewController.swift
VocabularyRepository 클래스를 통해 CoreData CRUD 기능 사용
=> CoreData로 CRUD 기능 추가 + Quiz 페이지 Feature 페이지 화면 연결

oewoboka/oewoboka.xcodeproj/project.pbxproj, oewoboka/oewoboka/Scenes/AddVocabularyPage/AddVocabularyViewController.swift, oewoboka/oewoboka/Scenes/AddVocabularyPage/VocabularyViewController.swift, oewoboka/oewoboka/Scenes/TabBarController.swift
=> [feat]추가하기UI구현

oewoboka/oewoboka/Scenes/VocaListPage/SelectedVocaViewController.swift, oewoboka/oewoboka/Scenes/VocaListPage/VocaListTableViewCell.swift, oewoboka/oewoboka/Scenes/VocaListPage/VocaListViewController.swift, oewoboka/oewoboka/Scenes/VocaListPage/VocaTableViewCell.swift, oewoboka/oewoboka/Scenes/VocaListPage/VocaViewController.swift
=> #3 [FEAT]: 코어데이터 연결하기

oewoboka/oewoboka.xcodeproj/project.pbxproj, oewoboka/oewoboka/Helper/BottomSheetViewController.swift, oewoboka/oewoboka/Model/Model.xcdatamodeld/Model.xcdatamodel/contents, oewoboka/oewoboka/Model/VocabularyEntity+CoreDataClass.swift, oewoboka/oewoboka/Model/VocabularyEntity+CoreDataProperties.swift, oewoboka/oewoboka/Model/VocabularyRepository.swift, oewoboka/oewoboka/Scenes/QuizCompletePage/QuizCompleteViewController.swift, oewoboka/oewoboka/Scenes/QuizPage/QuizViewController.swift, oewoboka/oewoboka/Scenes/QuizPage/View/CardView.swift, oewoboka/oewoboka/Scenes/VocaListPage/VocaListViewController.swift
=> [FEAT] 받아쓰기 기능 추가

oewoboka/oewoboka/Scenes/AddVocabularyPage/VocabularyViewController.swift, oewoboka/oewoboka/Scenes/VocaListPage/SelectedVocaViewController.swift, oewoboka/oewoboka/Scenes/VocaListPage/VocaListViewController.swift, oewoboka/oewoboka/Scenes/VocaListPage/VocaTableViewCell.swift, oewoboka/oewoboka/Scenes/VocaListPage/VocaViewController.swift
=> #3 [Merge]: 병합

oewoboka/oewoboka/Scenes/VocaListPage/SelectedVocaViewController.swift, oewoboka/oewoboka/Scenes/VocaListPage/VocaListTableViewCell.swift, oewoboka/oewoboka/Scenes/VocaListPage/VocaListViewController.swift, oewoboka/oewoboka/Scenes/VocaListPage/VocaViewController.swift
=> [Feat]: 데이터 연결 작업

oewoboka/oewoboka/Scenes/FeaturePage/FTModalPage/FTOPViewController.swift, oewoboka/oewoboka/Scenes/QuizPage/QuizViewController.swift, oewoboka/oewoboka/Scenes/QuizPage/View/CardView.swift, oewoboka/oewoboka/View/DefaultButton.swift
QuizPage 들어갈때 단어장 선택 안하면 아무것도 안보이는 버그 수정
=> [BUG] QuizPage 들어갈때 단어장 선택 안하면 아무것도 안보이는 버그 수정

oewoboka/oewoboka.xcodeproj/project.pbxproj, oewoboka/oewoboka/Helper/TanslatedManager.swift, oewoboka/oewoboka/Model/TransLateData.swift, oewoboka/oewoboka/Scenes/AddVocabularyPage/AddWordViewController.swift, oewoboka/oewoboka/Scenes/TabBarController.swift
=> #48 [FEAT] UI수정 및 api 연결

oewoboka/oewoboka.xcodeproj/project.pbxproj, oewoboka/oewoboka/Scenes/QuizCompletePage/QuizCompleteViewController.swift, oewoboka/oewoboka/Scenes/VocaListPage/VocaListTableViewCell.swift, oewoboka/oewoboka/View/CircleProgressBar.swift
CircleProgressBar 이니셜라이저에 rate 제거
=> [feat] CircleProgressBar 이니셜라이저에 rate 제거

oewoboka/oewoboka/Helper/BottomSheetViewController.swift
BottomSheetViewController 상단 클릭하거나 조금만 드래그 한 경우 최상단으로 이동하는 버그 수정
=> [BUG] BottomSheetViewController 상단 클릭하거나 조금만 드래그 한 경우 최상단으로 이동하는 버그 수정

oewoboka/oewoboka/Scenes/FeaturePage/FTModalPage/FTOPViewController.swift
[FEAT] 하나 이상 단어장 선택안하면 경고창 및 화면전환 안됨
=> [FEAT] 하나 이상 단어장 선택안하면 경고창 및 화면전환 안됨

oewoboka/oewoboka.xcodeproj/project.pbxproj, oewoboka/oewoboka/Extenstions/Int.swift, oewoboka/oewoboka/Scenes/FeaturePage/FTModalPage/FTOPViewController.swift, oewoboka/oewoboka/Scenes/QuizCompletePage/QuizCompleteViewController.swift, oewoboka/oewoboka/Scenes/QuizCompletePage/View/FeedBackStackView.swift, oewoboka/oewoboka/Scenes/QuizPage/QuizViewController.swift, oewoboka/oewoboka/Scenes/QuizPage/QuziViewModel.swift, oewoboka/oewoboka/Scenes/QuizPage/View/TimerSettingView.swift, oewoboka/oewoboka/View/CircleProgressBar.swift
=> [FEAT]시간을 설정하고 시험을 테스트를 보듯 하는 기능 추가

oewoboka/oewoboka/Scenes/FeaturePage/FTModalPage/FTOPViewController.swift, oewoboka/oewoboka/Scenes/FeaturePage/FTModalPage/FTOPViewModel.swift, oewoboka/oewoboka/Scenes/FeaturePage/VocaListSelectedPage/VocaListSelectedController.swift, oewoboka/oewoboka/Scenes/QuizPage/QuizViewController.swift
단어장을 모두 선택하지 않은경우 모두 선택으로 바뀌도록 기능 추가
=> [Feat] 단어장을 모두 선택하지 않은경우 모두 선택으로 바뀌도록 기능 추가

oewoboka/oewoboka/Scenes/QuizCompletePage/QuizCompleteViewController.swift, oewoboka/oewoboka/Scenes/QuizCompletePage/View/FeedBackStackView.swift, oewoboka/oewoboka/Scenes/QuizPage/QuizViewController.swift, oewoboka/oewoboka/Scenes/QuizPage/QuziViewModel.swift, oewoboka/oewoboka/Scenes/QuizPage/View/CardView.swift, oewoboka/oewoboka/Scenes/QuizPage/View/QuizControlStackView.swift
=> [Refactor] mvvm 패턴으로 리펙토링

oewoboka/oewoboka/Scenes/QuizPage/QuizViewController.swift, oewoboka/oewoboka/Scenes/QuizPage/QuziViewModel.swift, oewoboka/oewoboka/Scenes/QuizPage/View/CardView.swift, oewoboka/oewoboka/Scenes/QuizPage/View/QuizControlStackView.swift
QuizPage UI 수정 + CardView 아래쪽 버튼 클릭 이벤트 추가 + 갯수 제한 기능
=> [Fix] QuizPage UI 수정 + CardView 아래쪽 버튼 클릭 이벤트 추가 + 갯수 제한 기능

oewoboka/oewoboka/Scenes/VocaListPage/VocaViewController.swift
단어를 생성하지 않고 +버튼만 누르고 나와도 단어 갯수가 증가하는 버그 수정
=> [BUG] 단어를 생성하지 않고 +버튼만 누르고 나와도 단어 갯수가 증가하는 버그 수정

oewoboka/oewoboka/Scenes/VocaListPage/VocaListTableViewCell.swift, oewoboka/oewoboka/Scenes/VocaListPage/VocaListViewController.swift
=> [FEAT] 단어장 삭제 기능 추가
